### ISSUE TITLE
Schema fragment for definition of "q" to be referenced from inside Queryables

### ISSUE THREAD

**Issue by ycespb** [stac-api-extensions/freetext-search#4]
Filtering according to OGC API-Features Part 3 "Filtering" has now a conformance class "Queryables" which can be supported without the need to support also the complexity of the "filter" keyword and a CQL filter etc.

Therefore, it would be useful to include a JSON schema file in the "stac-freetext-search" extension that can be used as `$ref` target as explained  [here - see "Notice.." below the example](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/filter#interaction-with-endpoints).

It could then be included in a Queryables response as shown below (without the need to include additional compliance classes for this parameter).

"q" : {
      "description" : "Free text search parameter",
      "$ref": "https://github.com/cedadev/stac-freetext-search/schema.json#/properties/q"
},

This additional parameter (with its attached semantics) can then be used as HTTP query parameter (Part 3 "queryables-query-parameters" conformance class) or in combination with an actual filter (Part 3 "filter" conformance class).

By a bit rewording the definition of 'q', it might then be used also for both "STAC items" and 'STAC collection" searches and appear in the corresponding "Queryables" object.
In its most basic form, the schema.org file might be just this (could be extended with "pattern" etc...):

``````
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://github.com/cedadev/stac-freetext-search/schema.json#",
	"title": "Free text search parameter",
	"type": "object",
	"properties": {
		"q": {
			"title": "Free text search parameter",
			"description": "Free test search parameter",
			"type": "string"
		}
	}
}

````

**Comment by m-mohr** [comment]
I don't think this is necessary if the conformance classes are implemented correctly?
