### ISSUE TITLE
Release v1.0.0-rc.1

### ISSUE THREAD

**Issue by m-mohr** [stac-api-extensions/freetext-search#8]
Thanks for merging #7 @agstephens . Could you also release this extension as `v1.0.0-rc.1`, please?

PS: If you want, we could also migrate this to the stac-api-extensions organization. The extension is somewhat incorrectly already using the scope/URI of the organization: `https://api.stacspec.org/...`

**Comment by rhysrevans3** [comment]
I've published the release and am happy for your to migrate this to the stac-api-extensions organisation. If you let me know when this is done I can archive this repo.

**Comment by m-mohr** [comment]
Thanks. I'd need admin privileges in this repo so that I can move it over.  @rhysrevans3 
You'd keep your permissions after moving it, of course.

**Comment by rhysrevans3** [comment]
You should have an admin invite now 👍

**Comment by m-mohr** [comment]
Thanks, moved. If there are any issues with permissions or so, please let me know and I'll fix it.
